# Generated by Django 4.2.29 on 2026-03-18 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50)),
                ('familia', models.CharField(blank=True, default='', max_length=150)),
                ('familia_normalizada', models.CharField(blank=True, default='', max_length=150)),
                ('subfamilia', models.CharField(blank=True, default='', max_length=150)),
                ('descrip1', models.CharField(blank=True, default='', max_length=500)),
                ('descrip2', models.CharField(blank=True, default='', max_length=500)),
                ('unidad', models.CharField(blank=True, default='', max_length=20)),
                ('cluster_id', models.IntegerField(blank=True, null=True)),
                ('es_duplicado', models.BooleanField(default=False)),
                ('grupo_duplicado', models.IntegerField(blank=True, db_index=True, null=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('cargado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'serviparamo_catalogo_skus',
                'indexes': [models.Index(fields=['familia'], name='serviparamo_familia_2b1c26_idx'), models.Index(fields=['familia_normalizada'], name='serviparamo_familia_968379_idx'), models.Index(fields=['es_duplicado'], name='serviparamo_es_dupl_366bce_idx')],
            },
        ),
        migrations.CreateModel(
            name='CatalogoEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField()),
                ('texto_fuente', models.TextField()),
                ('generado_en', models.DateTimeField(auto_now=True)),
                ('sku', models.OneToOneField(db_column='sku_id', on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='serviparamo.catalogosku')),
            ],
            options={
                'db_table': 'serviparamo_catalogo_embeddings',
            },
        ),
    ]
