# Generated by Django 4.2.29 on 2026-03-18 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviparamo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogosku',
            old_name='subfamilia',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='catalogosku',
            old_name='descrip1',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='catalogosku',
            old_name='descrip2',
            new_name='nombre1',
        ),
    ]
